parameters:
    pim_analytics.controller.data.class:        Akeneo\Platform\Bundle\AnalyticsBundle\Controller\DataController
    pim_analytics.controller.system_info.class: Akeneo\Platform\Bundle\AnalyticsBundle\Controller\SystemInfoController

services:
    pim_analytics.controller.data:
        class: '%pim_analytics.controller.data.class%'
        arguments:
            - '@pim_analytics.data_collector.chained'

    pim_analytics.controller.system_info:
        class: '%pim_analytics.controller.system_info.class%'
        arguments:
            - '@templating'
            - '@pim_analytics.data_collector.chained'

    pim_analytics.controller.changelog:
        class: Akeneo\Platform\Bundle\AnalyticsBundle\Controller\ChangelogController
        arguments:
            - ['%pim_ce_dev_src_folder_location%']
